# Generated by Django 5.2.5 on 2025-09-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_availability_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.trainerprofile'),
        ),
    ]
