# Generated by Django 5.2.5 on 2025-10-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
