# Generated by Django 5.2.5 on 2025-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_memberprofile_is_approved_trainerprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfitnessclass',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
