# Generated by Django 5.2.5 on 2025-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_groupfitnessclass_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='join_date',
            field=models.DateTimeField(),
        ),
    ]
