# Generated by Django 5.2.5 on 2025-10-07 09:53
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_booking_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='membership_end',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
    ]
