# Generated by Django 5.2.5 on 2025-10-07 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_memberprofile_membership_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfitnessclass',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_end',
            field=models.DateTimeField(),
        ),
    ]
