# Generated by Django 5.2.5 on 2025-10-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_groupfitnessclass_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
