# Generated by Django 5.2.5 on 2025-10-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_memberprofile_membership_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='is_approved',
        ),
    ]
