# Generated by Django 5.2.5 on 2025-10-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_groupfitnessclass_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfitnessclass',
            name='equipment',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
