# Generated by Django 5.2.5 on 2025-10-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_groupfitnessclass_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfitnessclass',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('finished', 'Finished')], default='available', max_length=10),
        ),
    ]
