# Generated by Django 5.2.5 on 2025-10-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_groupfitnessclass_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('trainer', 'date', 'start_time', 'end_time')},
        ),
    ]
