# Generated by Django 5.2.5 on 2025-10-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
    ]
