# Generated by Django 5.2.5 on 2025-10-11 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_availability_date_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
